namespace: emb

deployment:
  name: text-vectorizer
  replicaCount: 1
  labels:
    appName: text-vectorizer
  container:
    name: text-vectorizer
    portNumber: 5000
    args: []
  image:
    name: khoatomato/embedding_vietnamese
    version: v0.0
    imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 1.5Gi
    limits:
      cpu: 2
      memory: 10Gi

service:
  name: emb-svc
  type: ClusterIP 
  httpPort:
    enable: true
    port: 81
    targetPort: 5000
